# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: required

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'lintr::lint_package()'
