# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: required

r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'library(covr);codecov()'
  - bash <(curl -s https://codecov.io/bash)
